[WIP][REF] Skip builds if commit message has [ci-skip]
OCA/runbot-addons pull request #117
Opened 2016-12-22 01:00 UTC by hugho-ad

### [WIP]
FIX https://github.com/OCA/runbot-addons/issues/116

2016-12-22 01:01 UTC, hugho-ad commented
@moylop260 what do you think ?

2016-12-22 01:36 UTC, moylop260 requested changes
Could you add a test creating a build with the subject "ci-skip" please?

2016-12-22 01:36 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +    def skip_check(self, build):
You are receiving a parameter build but I didn't see a value sent from invoke

2016-12-22 01:36 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +        build.skip_check()
You are returning a value but is not processed

2016-12-22 03:44 UTC, moylop260 commented on runbot_travis2docker/models/runbot_build.py
> +    def skip_check(self, cr, uid, build, context):
assign None by default to context parameter

2016-12-22 03:46 UTC, moylop260 commented on runbot_travis2docker/tests/test_runbot_build.py
> +        'Create build and run all jobs'
Use a comment or a docstring
This is a unassigned string

2016-12-22 03:48 UTC, moylop260 commented
Could you force another commit in order to force build in travis?

2016-12-22 04:51 UTC, hugho-ad commented
@moylop260 travis green

2016-12-22 04:56 UTC, moylop260 approved these changes
Thanks

2016-12-22 04:57 UTC, moylop260 commented
@lasley @pedrobaeza @alan196 your feedback is welcome

2016-12-22 06:23 UTC, lasley approved these changes
Neat, this will be great for docs branches 👍

2016-12-22 09:04 UTC, pedrobaeza approved these changes
And for Transifex commits (when I implement it that change)

2016-12-26 17:17 UTC, hugho-ad commented
@moylop260 this pr can be merged ?

2016-12-26 17:54 UTC, merged